#!/bin/bash

echo -n "Building parser... "
	rm -f scanner.yy.c
	rm -f parser.tab.*pp
	rm -f hw4
	flex scanner.lex
	bison -d parser.ypp
	g++ -o hw4 *.c *.cpp
echo "Done"
echo

cd PassedTests

dos2unix * 2>/dev/null

for f in `ls *.in`; do
	res_file=`sed "s/\.in/.result/g" <<< "$f"`
	out_file=`sed "s/\.in/.out/g" <<< "$f"`	
	echo -n "Running test $f...   "
	../hw4 < $f > $res_file	
	diff $out_file $res_file 1>/dev/null
	if [[ $? -eq 0 ]]; then
		echo "Pass"
		rm -f $res_file
	else
		echo "Fail"
		diff $out_file $res_file
	fi
	echo "~~~~~~~~~~~~ "
done
